### ISSUE TITLE
Issue: History Saving list hiding the genre and year dropdown

### ISSUE THREAD

**Issue by sid0000007** [daccotta-org/daccotta#167]
Fixing UI
<img width="896" alt="Screenshot 2024-10-14 at 11 53 41 PM" src="https://github.com/user-attachments/assets/c8d45ae0-adb1-429f-ad73-15bc48dd8550">

What to be fix ? 

- Place the Year and Genre dropdown to right of  the search bar. 
- Keep the history List dropdown same 
-  change the font and make the text  only visible (No time and date)

**Comment by nidhi2026** [comment]
@sid0000007 If this issue is not fixed yet, Can I work on it

**Comment by sid0000007** [comment]
> @sid0000007 If this issue is not fixed yet, Can I work on it

Go ahead. Join Discord for any possible help .

**Comment by nidhi2026** [comment]
@sid0000007 
Instead of placing it to the right of the search bar, I placed it above the search so I can handle its responsiveness when the screen is small, too.
Is it fine, or should I make any changes? Thank you

Here is an attached video of the responsiveness

https://github.com/user-attachments/assets/6ffd9826-b7bf-4622-a8bb-469510c4921d
