### ISSUE TITLE
Feature: Add toggle button for dark/light theme

### ISSUE THREAD

**Issue by mehul-m-prajapati** [daccotta-org/daccotta#80]
Feature: Add toggle button for dark/light theme 
**Position**:  will be on Sidebar as of now.

**Comment by AshuKr22** [comment]
hey @mehul-m-prajapati  as of now our themes are a little messed up because of some conficts between shadcn and daisy ui . so some places are forcing black color on the background . i think it will be a lot of trouble to implement a dark/light theme. also a lot of ott platforms keep only a light background because otherwise the bright background would overshadow the movie posters. so before working on it can you please show a sample of what the background would look like?

**Comment by mehul-m-prajapati** [comment]
I understand the concerns about the theme conflicts between shadcn and Daisy UI. It does sound like implementing a dark/light theme could be quite challenging, especially with the issues related to the background colors.
